os:
- linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
language: rust
rust:
- nightly-2019-03-23
cache: cargo

before_script:
# install z3
- wget -O z3.zip https://github.com/Z3Prover/bin/blob/10fafc192673e9ec80ae8abff38bcc1e1a3a0a9c/nightly/z3-4.8.5.606754c09a68-x64-ubuntu-14.04.zip?raw=true
- unzip z3
- sudo mv z3-4.8.5.606754c09a68-x64-ubuntu-14.04/include/* /usr/include/
- sudo mv z3-4.8.5.606754c09a68-x64-ubuntu-14.04/bin/libz3.* /usr/lib/x86_64-linux-gnu/
# install formatter
- rustup component add rustfmt-preview
# install linter
- rustup component add clippy-preview
# install code coverage tool
- RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin || true

script:
# Exit immediately if a command exits with a non-zero status.
- set -e
# Run format checks
- cargo fmt --all -- --check
# Run lint checks
- cargo clippy -- -D warnings
# Build
- cargo build
# Run unit and integration tests
- RUST_BACKTRACE=1 cargo test
# Run code coverage tests
- cargo clean -p rust_smt
- cargo tarpaulin --ignore-tests -v --out Xml || true
- bash <(curl -s https://codecov.io/bash)
